knp_paginator:
    page_range: 5 # Number of pages displayed in the pagination menu
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true # Ensure distinct results
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
