when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: true


    framework:
        profiler: { only_exceptions: false }


when@test:
    web_profiler:
        toolbar: true
        intercept_redirects: true


    framework:
        profiler: { collect: true }
