version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
<<<<<<< HEAD
###< doctrine/doctrine-bundle ###



=======
###< doctrine/doctrine-bundle ###
>>>>>>> a18cdd6a6674efbecf899883a1a5a485e854ff57

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
