# index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_projet_back_project_markers:
    path: /project/markers
    controller: App\Controller\ProjetBackController::projectMarkers
    methods: [GET]

search_endpoint:
    path: /search-endpoint
    controller: App\Controller\ProjetBackController::search
    methods: [GET]


# config/routes.yaml

