# index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_projet_back_project_markers:
    path: /project/markers
    controller: App\Controller\ProjetBackController::projectMarkers
    methods: [GET]
