# index:
#    path: /
#    controller: App\Controller\DefaultController::index


authenticate:
    path: /carte/bancaire/back/authenticate
    controller: App\Controller\CarteBancaireBackController::authenticate
    methods: ['POST']